name: Deploy release

run-name: Deploy ${{ github.repository }}

on:
  release:
    types: published
  workflow_dispatch:

jobs:
  # Since deployment uses a dedicated account, we only need to pull the repository from that account.
  # Deployments are configured to run automatically.
  deploy:
    runs-on: ubuntu-latest

    outputs:
      repo_name: ${{ steps.extract.outputs.repo_name }}

    steps:
      - name: Extract repo name
        id: extract
        run: echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUTS

      - name: Display repo name
        run: echo ${{ steps.extract.outputs.repo_name }}

      - uses: actions/checkout@v5
        with:
          repository: "${{ env.SHARED_ACCOUNT }}/${{ steps.extract.outputs.repo_name }}"
          fetch_depth: 0
          token: ${{ secrets.SHARED_ACCOUNT_TOKEN }}

      - name: Pull latest changes
        run: |
          git fetch --tags
          git reset --hard origin/main

      - name: Push changes
        run: git push origin main --force

